More robust checks

diff --git a/usr/bin/sandbox-app-launcher b/usr/bin/sandbox-app-launcher
--- a/usr/bin/sandbox-app-launcher
+++ b/usr/bin/sandbox-app-launcher
@@ -119,6 +119,23 @@ error_handler() {
 
 trap "error_handler" ERR
 
+run_if_root() {
+  if [ "${sal_is_run_with_root}" = "true" ]; then
+    "${@}"
+  else
+    echo "ERROR: The setup for this program is incomplete. To fix, please execute:
+
+sudo sandbox-app-launcher setup ${app_name}
+
+(Debugging information: ${@})" >&2
+    exit 1
+  fi
+}
+
+if [ "$(id -u)" = "0" ]; then
+  sal_is_run_with_root=true
+fi
+
 setup() {
   if ! [ "$(id -u)" = "0" ]; then
     echo "ERROR: The setup must be run as root." >&2
@@ -126,13 +143,23 @@ setup() {
   fi
 
   for dir in "${main_app_dir}" "${auto_dir}" "${wrapper_dir}" "${wrapper_dir_wx}" "${appdata_dir}"; do
-    if ! [ "$(stat -c %a "${dir}")" = "755" ]; then
-        chmod 755 "${dir}"
+    ## Check if the required directories exist.
+    if ! [ -d "${dir}" ]; then
+      echo "ERROR: Directory '${dir}' does not exist. This package was not installed properly." >&2
+      exit 1
+    ## Fix permissions.
+    elif ! [ "$(stat -c %a "${dir}")" = "755" ]; then
+      chmod 755 "${dir}"
     fi
   done
 
-  if ! [ "$(stat -c %a "${shared_dir}")" = "1777" ]; then
-    chmod 1777 "${dir}"
+  ## Check if the shared directory exists.
+  if ! [ -d "${shared_dir}" ]; then
+    echo "ERROR: Directory '${shared_dir}' does not exist. This package was not installed properly." >&2
+    exit 1
+  ## Fix permissions.
+  elif ! [ "$(stat -c %a "${shared_dir}")" = "1777" ]; then
+    chmod 1777 "${shared_dir}"
   fi
 
   ## Create the user that the sandboxed application will run as.
@@ -240,6 +267,16 @@ EOF
 }
 
 run_program() {
+  ## Fix permissions if running as root.
+  for dir in "${main_app_dir}" "${auto_dir}" "${wrapper_dir}" "${wrapper_dir_wx}" "${appdata_dir}"; do
+    if ! [ "$(stat -c %a "${dir}")" = "755" ]; then
+      run_if_root chmod 755 "${dir}"
+    fi
+  done
+  if ! [ "$(stat -c %a "${shared_dir}")" = "1777" ]; then
+    run_if_root chmod 1777 "${shared_dir}"
+  fi
+
   ## TODO: X11 sandbox - not needed if we switch to wayland
   ## TODO: IPC namespace
   ## TODO: Network namespace - probably via ip netns
@@ -355,13 +392,13 @@ remove_app() {
   if getent passwd | grep -q "${app_user}"; then
     userdel --remove --force "${app_user}"
   else
-    echo "ERROR: User '${app_user}' does not exist."
+    echo "ERROR: User '${app_user}' does not exist." >&2
   fi
 
   if [ -f "${wrapper_script}" ]; then
     rm "${wrapper_script}"
   else
-    echo "ERROR: File '${wrapper_script}' does not exist."
+    echo "ERROR: File '${wrapper_script}' does not exist." >&2
   fi
 }
 
@@ -373,7 +410,7 @@ elif [ "${start_program}" = "1" ]; then
   else
     echo "ERROR: The sandbox for this program has not been set up yet. Please execute:
 
-sudo sandbox-app-launcher setup ${app_name}"
+sudo sandbox-app-launcher setup ${app_name}" >&2
   fi
 elif [ "${remove}" = "1" ]; then
   remove_app
