Tor Browser support

diff --git a/usr/bin/sandbox-app-launcher b/usr/bin/sandbox-app-launcher
--- a/usr/bin/sandbox-app-launcher
+++ b/usr/bin/sandbox-app-launcher
@@ -9,9 +9,11 @@ app_name="${1}"
 shift 1
 : ${app_path:="$(type -P "${app_name}" || true)"}
 
-if ! [[ "${app_name}" =~ [0-9a-zA-Z/] ]] || ! [[ "${app_path}" =~ [0-9a-zA-Z/] ]]; then
-  echo "ERROR: Invalid character."
-  exit 1
+if ! [[ "${app_name}" =~ [0-9a-zA-Z/] ]]; then
+  if ! [[ "${app_path}" =~ [0-9a-zA-Z/] ]]; then
+    echo "ERROR: Invalid character."
+    exit 1
+  fi
 fi
 
 main_app_dir="/usr/share/sandbox-app-launcher"
@@ -25,6 +27,10 @@ seccomp_filter="${auto_dir}/seccomp-filter.bpf"
 wx_whitelist="${main_app_dir}/wx_whitelist"
 shared_dir="${appdata_dir}/shared"
 bwrap_args=""
+
+if [ "${app_name}" = "torbrowser" ]; then
+  app_path="${app_homedir}/.tb/tor-browser/Browser/start-tor-browser"
+fi
 
 error_handler() {
   echo "
@@ -169,6 +175,14 @@ run_program() {
     bwrap_args+="--bind ${shared_dir} ${shared_dir} --bind /shared /shared "
   elif [ "${shared_storage}" = "read-only" ]; then
     bwrap_args+="--ro-bind ${shared_dir} ${shared_dir} --ro-bind /shared /shared "
+  fi
+
+  ## Install Tor Browser.
+  if [ "${app_name}" = "torbrowser" ]; then
+    if ! [ -d "${app_homedir}/.tb" ]; then
+      echo -e "INFO: Installing Tor Browser in sandbox...\n"
+      sudo -H -u "${app_user}" HOME="${app_homedir}" tb_no_start="true" torbrowser
+    fi
   fi
 
   sudo -H -u "${app_user}" bash -c "
