Split setup and run_program into separate command line arguments

diff --git a/usr/bin/sandbox-app-launcher b/usr/bin/sandbox-app-launcher
--- a/usr/bin/sandbox-app-launcher
+++ b/usr/bin/sandbox-app-launcher
@@ -5,10 +5,36 @@
 
 set -e
 
-if [ $# -eq 0 ]; then
-    echo "Usage: program [OPTIONS]" >&2
-    exit 1
-fi
+while :
+do
+      case $1 in
+      setup)
+        setup_sandbox="1"
+        shift
+        break
+        ;;
+      run)
+        start_program="1"
+        shift
+        break
+        ;;
+      help)
+        echo "Usage: sandbox-app-launcher [OPTION] [PROGRAM]
+
+  setup       Setup the sandbox for the program.
+  run         Execute the program within the sandbox.
+  
+Examples:
+  sandbox-app-launcher setup firefox
+  sandbox-app-launcher run firefox"
+        exit
+        ;;
+      *)
+        echo "ERROR: Invalid argument. See the 'help' command for details."
+        exit 1
+        ;;
+      esac
+done
 
 app_name="${1}"
 shift 1
@@ -41,6 +67,20 @@ if [ "${app_name}" = "torbrowser" ]; then
   app_path="${app_homedir}/.tb/tor-browser/Browser/start-tor-browser"
 fi
 
+if ! [ -x "${app_path}" ] && ! [ "${app_name}" = "torbrowser" ]; then
+  echo "ERROR: Could not find '${app_name}' in \$PATH." >&2
+  exit 1
+fi
+
+if [ "${app_name}" = "shared" ]; then
+  echo "ERROR: The app name cannot be 'shared'." >&2
+  exit 1
+fi
+
+if [ -f "/etc/sandbox-app-launcher/${app_name}.conf" ]; then
+  . "/etc/sandbox-app-launcher/${app_name}.conf"
+fi
+
 error_handler() {
   echo "
 ## sandbox-app-launcher BUG.
@@ -52,23 +92,9 @@ error_handler() {
 
 trap "error_handler" ERR
 
-if ! [ "$(id -u)" = "0" ]; then
-  echo "ERROR: Must run as root." >&2
-  exit 1
-fi
-
-if [ -f "/etc/sandbox-app-launcher/${app_name}.conf" ]; then
-  . "/etc/sandbox-app-launcher/${app_name}.conf"
-fi
-
 setup() {
-  if ! [ -x "${app_path}" ] && ! [ "${app_name}" = "torbrowser" ]; then
-    echo "ERROR: Could not find '${app_name}' in \$PATH." >&2
-    exit 1
-  fi
-
-  if [ "${app_name}" = "shared" ]; then
-    echo "ERROR: The app name cannot be 'shared'." >&2
+  if ! [ "$(id -u)" = "0" ]; then
+    echo "ERROR: The setup must be run as root." >&2
     exit 1
   fi
 
@@ -317,5 +343,14 @@ run_program() {
   killall -9 -u "${app_user}"
 }
 
-setup
-run_program "${@}"
+if [ "${setup_sandbox}" = "1" ]; then
+  setup
+elif [ "${start_program}" = "1" ]; then
+  if [ -d "${app_homedir}" ]; then
+    run_program "${@}"
+  else
+    echo "ERROR: The sandbox for this program has not been set up yet. Please execute:
+    
+sudo sandbox-app-launcher setup ${app_name}"
+  fi
+fi
